# Generated by Django 5.1.4 on 2026-07-14 11:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_department', models.ForeignKey(blank=True, limit_choices_to={'role': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Public holiday vs university-specific')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('degree_type', models.CharField(choices=[('BTECH', 'B.Tech'), ('MTECH', 'M.Tech'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('BSC', 'B.Sc'), ('MSC', 'M.Sc'), ('PHD', 'Ph.D'), ('DIPLOMA', 'Diploma'), ('OTHER', 'Other')], max_length=20)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('total_semesters', models.PositiveSmallIntegerField(default=8)),
                ('max_students_per_section', models.PositiveIntegerField(default=60)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.department')),
            ],
            options={
                'db_table': 'core_programs',
                'ordering': ['department__name', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(help_text='Room number e.g. B-201', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text='Display name e.g. Smart Class B201', max_length=100)),
                ('block', models.CharField(blank=True, help_text='Building block e.g. Block-B', max_length=50)),
                ('floor', models.PositiveSmallIntegerField(default=0)),
                ('room_type', models.CharField(choices=[('THEORY', 'Theory Classroom'), ('LAB', 'Laboratory'), ('SEMINAR', 'Seminar Hall'), ('AUDITORIUM', 'Auditorium')], default='THEORY', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=60)),
                ('lab_type', models.CharField(blank=True, help_text='For labs: Computer Lab, Physics Lab, Chemistry Lab etc.', max_length=100)),
                ('has_projector', models.BooleanField(default=True)),
                ('has_smart_board', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_computers', models.BooleanField(default=False)),
                ('computer_count', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Owning department (null = shared/common)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core.department')),
            ],
            options={
                'db_table': 'core_rooms',
                'ordering': ['block', 'floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')])),
                ('slot_number', models.PositiveSmallIntegerField(help_text='Ordering within the day')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('REGULAR', 'Regular Class'), ('LUNCH', 'Lunch Break'), ('BREAK', 'Short Break')], default='REGULAR', max_length=10)),
                ('label', models.CharField(blank=True, help_text="e.g. 'Period 1', 'Lunch'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_time_slots',
                'ordering': ['day', 'slot_number'],
                'unique_together': {('day', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('semester_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Laboratory'), ('TUTORIAL', 'Tutorial'), ('SEMINAR', 'Seminar'), ('PROJECT', 'Project')], default='THEORY', max_length=20)),
                ('weekly_hours', models.PositiveSmallIntegerField(default=3, help_text='Total theory hours OR 3 for lab (fixed 3-hour block)')),
                ('lab_hours_per_week', models.PositiveSmallIntegerField(default=0, help_text='Lab sessions per week (each session = 3 hours)')),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('is_elective', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('syllabus_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.program')),
            ],
            options={
                'db_table': 'core_subjects',
                'ordering': ['program__code', 'semester_number', 'name'],
                'unique_together': {('code', 'program')},
            },
        ),
    ]
