# Generated by Django 5.1.4 on 2026-07-14 11:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_start', models.PositiveSmallIntegerField()),
                ('year_end', models.PositiveSmallIntegerField()),
                ('label', models.CharField(help_text='e.g. 2024-25', max_length=20, unique=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scheduling_academic_years',
                'ordering': ['-year_start'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester_type', models.CharField(choices=[('ODD', 'Odd Semester'), ('EVEN', 'Even Semester'), ('SUMMER', 'Summer Term')], max_length=10)),
                ('name', models.CharField(help_text="e.g. 'Odd Semester 2024-25'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False, help_text='Lock to prevent further edits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='scheduling.academicyear')),
            ],
            options={
                'db_table': 'scheduling_semesters',
                'ordering': ['-start_date'],
                'unique_together': {('academic_year', 'semester_type')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. A, B, C or CS-3A', max_length=20)),
                ('semester_number', models.PositiveSmallIntegerField(help_text='Which semester of the program (e.g. 3 = 3rd semester)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('max_students', models.PositiveIntegerField(default=60)),
                ('current_strength', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_section', models.ForeignKey(blank=True, help_text='If auto-split from another section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_sections', to='scheduling.section')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheduling.semester')),
            ],
            options={
                'db_table': 'scheduling_sections',
                'ordering': ['program__code', 'semester_number', 'name'],
                'unique_together': {('name', 'program', 'semester', 'semester_number')},
            },
        ),
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekly_hours_override', models.PositiveSmallIntegerField(blank=True, help_text="Override subject's default weekly hours", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='faculty.facultyprofile')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='scheduling.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='scheduling.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.subject')),
            ],
            options={
                'db_table': 'scheduling_subject_allocations',
                'ordering': ['section__name', 'subject__name'],
                'unique_together': {('subject', 'section', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TimetableGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('INFEASIBLE', 'No Feasible Solution'), ('PARTIAL', 'Partial Solution')], default='PENDING', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False, help_text='The currently active timetable')),
                ('config', models.JSONField(default=dict, help_text='Solver parameters used')),
                ('solver_stats', models.JSONField(default=dict, help_text='OR-Tools solver statistics')),
                ('conflicts', models.JSONField(default=list, help_text='Conflict explanations if infeasible')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('solve_time_seconds', models.FloatField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='scheduling.semester')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduling_generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')])),
                ('is_lab_block', models.BooleanField(default=False, help_text='Part of a 3-hour lab block')),
                ('is_locked', models.BooleanField(default=False, help_text="Admin-locked, won't be moved on regeneration")),
                ('is_manual_override', models.BooleanField(default=False, help_text='Manually placed by admin')),
                ('soft_score', models.IntegerField(default=0, help_text='Soft constraint score for this slot')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='scheduling.subjectallocation')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.timetablegeneration')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='core.room')),
                ('time_slots', models.ManyToManyField(help_text='One slot for theory, up to 6 consecutive slots for labs', to='core.timeslot')),
            ],
            options={
                'db_table': 'scheduling_timetable_slots',
                'ordering': ['day', 'allocation__section__name'],
            },
        ),
    ]
