# Generated by Django 5.1.4 on 2026-07-14 11:02

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=False, help_text='False = unavailable in this window; True = preferred window')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('is_recurring', models.BooleanField(default=True, help_text='Weekly recurring vs one-time')),
                ('date', models.DateField(blank=True, help_text='Specific date (for one-time unavailability)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'faculty_availability',
                'ordering': ['faculty', 'day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOC_PROFESSOR', 'Associate Professor'), ('ASST_PROFESSOR', 'Assistant Professor'), ('LECTURER', 'Lecturer'), ('VISITING', 'Visiting Faculty'), ('HOD', 'Head of Department')], max_length=30)),
                ('specializations', models.JSONField(default=list, help_text='List of subject areas')),
                ('max_weekly_hours', models.PositiveSmallIntegerField(default=18, help_text='Maximum teaching hours per week', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('max_daily_hours', models.PositiveSmallIntegerField(default=6, help_text='Maximum teaching hours per day', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('can_take_lab', models.BooleanField(default=True, help_text='Faculty can supervise lab sessions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faculty_profiles',
                'ordering': ['department__name', 'user__last_name'],
            },
        ),
    ]
