# Generated by Django 5.1.4 on 2026-07-14 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('faculty', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyavailability',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_availability', to='scheduling.semester'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='core.department'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='preferred_subjects',
            field=models.ManyToManyField(blank=True, related_name='preferred_faculty', to='core.subject'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='faculty.facultyprofile'),
        ),
    ]
